### PR TITLE
Revert "update OpenSBI to v0.9"

### PR DESCRIPTION
**Pull request by kent-mcleod**
Reverts seL4/sel4bench-manifest#9

Test with: https://github.com/lsf37/opensbi/pull/1

### CODE REVIEW

**Comment by Ivan-Velickovic** [comment]
As @kent-mcleod discovered, what had happened was that a commit in OpenSBI (https://github.com/riscv-software-src/opensbi/commit/ebc8ebc0f84618b2cef8b9b77cc705e4c7c2d8d6) caused certain M-mode CSRs that seL4bench uses to stop being emulated. In particular, `mhpmevent` and `mhpmcounter`. It looks like that `hpmevent` does not have a U-Mode equivalent. So in order to get this information from non M-Mode, an SBI call using the SBI PMU extension will be needed if OpenSBI >= 0.8 was to be used.

**Review by Ivan-Velickovic — APPROVED** [review]

**Review by lsf37 — APPROVED** [review]
@kent-mcleod can you add the missing sign-off line?

**Comment by lsf37** [comment]
> As @kent-mcleod discovered, what had happened was that a commit in OpenSBI ([riscv-software-src/opensbi@ebc8ebc](https://github.com/riscv-software-src/opensbi/commit/ebc8ebc0f84618b2cef8b9b77cc705e4c7c2d8d6)) caused certain M-mode CSRs that seL4bench uses to stop being emulated. In particular, `mhpmevent` and `mhpmcounter`. It looks like that `hpmevent` does not have a U-Mode equivalent. So in order to get this information from non M-Mode, an SBI call using the SBI PMU extension will be needed if OpenSBI >= 0.8 was to be used.

Would that be hard or problematic to add or is it just work?

**Comment by Ivan-Velickovic** [comment]
> > As @kent-mcleod discovered, what had happened was that a commit in OpenSBI ([riscv-software-src/opensbi@ebc8ebc](https://github.com/riscv-software-src/opensbi/commit/ebc8ebc0f84618b2cef8b9b77cc705e4c7c2d8d6)) caused certain M-mode CSRs that seL4bench uses to stop being emulated. In particular, `mhpmevent` and `mhpmcounter`. It looks like that `hpmevent` does not have a U-Mode equivalent. So in order to get this information from non M-Mode, an SBI call using the SBI PMU extension will be needed if OpenSBI >= 0.8 was to be used.
> 
> Would that be hard or problematic to add or is it just work?

I think if you wanted to do a proper solution you would need something like https://sel4.atlassian.net/jira/software/c/projects/RFC/issues/RFC-9.

**Comment by kent-mcleod** [comment]
The `hw-test` tests seem to be testing 0.9 still.

**Comment by lsf37** [comment]
> The `hw-test` tests seem to be testing 0.9 still.

Yes, it turns out my test setup doesn't actually work for manifest repo PRs, because it doesn't recognise that it needs to do things slightly different when we're updating the manifest repo itself. It's a bit more involved than I initially thought, so it'll take a bit to implement.

In the meantime, I created a fake PR that models the manifest change and should cause CI to test the correct version.

**Comment by lsf37** [comment]
Ok, `hifive` has passed with this, and it has tested with OpenSBI 0.8, so I'll merge now.

**Pull request merged**
